export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';

export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const EDIT_USER = 'EDIT_USER';
export const POPULATE_USERS = 'POPULATE_USERS';

export const REQUEST_ADD_USER = 'REQUEST_ADD_USER';
export const REQUEST_DELETE_USER = 'REQUEST_DELETE_USER';
export const REQUEST_EDIT_USER = 'REQUEST_EDIT_USER';
export const REQUEST_POPULATE_USERS = 'REQUEST_POPULATE_USERS';

export const ADD_PAGE = 'ADD_PAGE';
export const DELETE_PAGE = 'DELETE_PAGE';
export const EDIT_PAGE = 'EDIT_PAGE';
export const POPULATE_PAGES = 'POPULATE_PAGES';

export const REQUEST_ADD_PAGE = 'REQUEST_ADD_PAGE';
export const REQUEST_DELETE_PAGE = 'REQUEST_DELETE_PAGE';
export const REQUEST_EDIT_PAGE = 'REQUEST_EDIT_PAGE';
export const REQUEST_POPULATE_PAGES = 'REQUEST_POPULATE_PAGES';
export const REQUEST_GET_MAIN_PAGES = 'REQUEST_GET_MAIN_PAGES';

export const ADD_TEMPLATE = 'ADD_TEMPLATE';
export const DELETE_TEMPLATE = 'DELETE_TEMPLATE';
export const EDIT_TEMPLATE = 'EDIT_TEMPLATE';
export const POPULATE_TEMPLATES = 'POPULATE_TEMPLATES';
export const POPULATE_MAIN_PAGES = 'POPULATE_MAIN_PAGES';

export const REQUEST_ADD_TEMPLATE = 'REQUEST_ADD_TEMPLATE';
export const REQUEST_DELETE_TEMPLATE = 'REQUEST_DELETE_TEMPLATE';
export const REQUEST_EDIT_TEMPLATE = 'REQUEST_EDIT_TEMPLATE';
export const REQUEST_POPULATE_TEMPLATES = 'REQUEST_POPULATE_TEMPLATES';

export const ADD_FILE = 'ADD_FILE';
export const DELETE_FILE = 'DELETE_FILE';
export const EDIT_FILE = 'EDIT_FILE';
export const POPULATE_FILES = 'POPULATE_FILES';
export const UPLOAD_FILE = 'UPLOAD_FILE';

export const REQUEST_ADD_FILE = 'REQUEST_ADD_FILE';
export const REQUEST_DELETE_FILE = 'REQUEST_DELETE_FILE';
export const REQUEST_EDIT_FILE = 'REQUEST_EDIT_FILE';
export const REQUEST_POPULATE_FILES = 'REQUEST_POPULATE_FILES';
export const REQUEST_UPLOAD_FILE = 'REQUEST_UPLOAD_FILE';

export const SET_STATUS_REQUEST = 'SET_STATUS_REQUEST'
export const SET_ERROR_REQUEST = 'SET_ERROR_REQUEST'
export const SET_REQUEST_RESPONSE = 'SET_REQUEST_RESPONSE'

export const NAVIGATE = 'NAVIGATE';
